import { Toaster } from "@/components/ui/sonner";
import ReduxProvider from "@/provider/redux-provider";
import { SessionProvider } from "@/provider/session-provider";
import { ThemeProvider } from "@/provider/theme-provider";
import "@/styles/globals.css";
import type { Metadata } from "next";

export const metadata: Metadata = {
    title: "TaskSync - TaskManager Application",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body
                className={`antialiased`}
                suppressHydrationWarning
            >
                <SessionProvider>
                    <ThemeProvider
                        attribute="class"
                        defaultTheme="light"
                        enableSystem
                        disableTransitionOnChange
                    >
                        <ReduxProvider>{children}</ReduxProvider>
                        <Toaster richColors={true} expand={false} />
                    </ThemeProvider>
                </SessionProvider>
            </body>
        </html>
    );
}
